<?= $this->doctype() ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Join - Teste Prático')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('/vendors/FontAwesome/css/fontawesome-all.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/jquery-maskmoney.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))           
        ?>
        
       
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-azul" role="navigation">
            <div class="container">
                <div class="navbar-header">                   
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo.png') ?>" height="34" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Teste prático
                    </a>
                </div>                
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
<!--                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>-->
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
